name: publish-release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build and publish to pypi.org
      run: |
        pipx install poetry==1.7.1
        poetry publish --build -u __token__ -p ${{ secrets.pypi_upload_token }}
